SilveradoPolicy/silverado

src/components/header.js

active nav item updated

---

src/components/altHero.js
src/components/fullWidthImageWithText.js
src/components/indexSubHero.js
src/components/listComponent.js
src/components/pillars.js

added bold text throughout site

---

src/components/advisoryBoard.js
src/components/copyWithCTA.js
src/components/eventList.js
src/components/footer.js
src/components/fullWidthImage.js
src/components/fullWidthImageWithText.js
src/components/header.js
src/components/indexHero.js
src/components/indexSubHero.js
src/components/listComponent.js
src/components/pillars.js
src/components/strategicCouncil.js

fixed R + L padding

---

package-lock.json
package.json
src/components/indexHero.js
src/components/pillars.js
src/pages/about.js
src/pages/ideas.js
src/pages/index.js
src/pages/initiatives.js

Katie enhancement 34 update copy

---

src/components/nav/mobileNav.js

text-align right

---

src/components/advisoryBoard.js
src/components/copyWithCTA.js
src/pages/about.js

edits for about page

---

src/pages/initiatives.js

remove cta

---

src/components/listComponent.js
src/pages/ideas.js

idea page edits

---

src/components/pillars.js
src/pages/about.js
src/pages/ideas.js
src/pages/index.js
src/pages/initiatives.js

update to copy

---

src/components/altHero.js

Fix hero height issue on small screens

---

src/components/copyWithCTA.js
src/pages/about.js
src/pages/index.js
src/pages/initiatives.js

add top gradient option

---

src/components/listComponent.js
src/pages/ideas.js

update list component to match design

---

src/components/altHero.js
tailwind.config.js

add min-height: 75vh option

---

src/components/pillars.js

update body copy to #000000

---

src/components/copyWithCTA.js

increase top padding

---

src/components/altHero.js

decrease heading font size on small screens

---

src/components/altHero.js

set font weight to thin

---

src/components/eventList.js

set x margin to auto

---

src/components/advisoryBoard.js
src/components/copyWithCTA.js
src/components/eventList.js
src/components/footer.js
src/components/fullWidthImage.js
src/components/fullWidthImageWithText.js
src/components/header.js
src/components/indexHero.js
src/components/indexSubHero.js
src/components/listComponent.js
src/components/pillars.js
src/components/strategicCouncil.js

move breakpoint from md: to lg:

---

src/components/advisoryBoard.js
src/components/copyWithCTA.js
src/components/eventList.js
src/components/footer.js
src/components/fullWidthImage.js
src/components/fullWidthImageWithText.js
src/components/header.js
src/components/indexHero.js
src/components/indexSubHero.js
src/components/listComponent.js
src/components/pillars.js
src/components/strategicCouncil.js

update padding breakpoint for container elements

---

web/src/components/pillarCardList.js

remove justify-center and margin on wrapper, add container

---

web/src/components/pillarCardList.js

add marginbottom to card title

---

web/src/components/blogPostList.js
web/src/pages/eventpreview-template.js
web/src/pages/news.js

* Change filter html from links to buttons
* Remove isActive prop, use isActive class instead
* Change styling from text-decoration to :after element to match designs

Generate news/blog filters from sanity categories

---

studio/schemas/objects/bodyPortableText.js
web/src/components/blogContent.js
web/src/components/blogHero.js

@asasmith also changed the height on the heroImage on the Individual Blog Page

Change height on heroImage, decrease subtitle font size, and remove h1 option on individual blog page
